version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-86-116-94.compute-1.amazonaws.com
            database: ddmqj5mgr1qj0g
            user: nyflktcfnxwnpz
            password: 80c8b5d67cd1bc1f5d80d7dab8431c683301f0aa62032d5efe4a836b6afcb6fe
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
